#
# i3-nord-dotfiles - LightDM GTK Greeter (tema Nord)
# Se instala en /etc/lightdm/lightdm-gtk-greeter.conf
#
[greeter]
# Fondo: mismo wallpaper Nord del escritorio (color de respaldo Nord0)
background = /usr/share/backgrounds/nord.png
background-color = #2E3440

# Temas GTK / iconos / cursor
theme-name = Nordic
icon-theme-name = Papirus-Dark
cursor-theme-name = Bibata-Modern-Ice

# Fuente
font-name = JetBrainsMono Nerd Font 11

# Ventana de acceso
position = 50%,center 50%,center
default-user-image = #avatar-default
xft-antialias = true
xft-hintstyle = hintfull
xft-rgba = rgb

# Panel superior
clock-format = %a %d %b  %H:%M
indicators = ~host;~spacer;~clock;~spacer;~session;~language;~a11y;~power

# Estetica
hide-user-image = false
round-user-image = true
highlight-logo = false
highlight-active-user = false
